[2025-03-18T14:13:31.943+0200] {processor.py:186} INFO - Started process (PID=31265) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:13:31.944+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:13:31.947+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:13:31.947+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:13:31.951+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:13:31.951+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:13:31.952+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:13:31.952+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:13:31.952+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:13:31.964+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T14:14:37.687+0200] {processor.py:186} INFO - Started process (PID=31561) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:14:37.688+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:14:37.691+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:14:37.690+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:14:37.695+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:14:37.694+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:14:37.695+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:14:37.695+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:14:37.695+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:14:37.707+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T14:15:44.636+0200] {processor.py:186} INFO - Started process (PID=31752) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:15:44.638+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:15:44.642+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:15:44.641+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:15:44.647+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:15:44.646+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:15:44.647+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:15:44.647+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:15:44.648+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:15:44.664+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-03-18T14:16:54.889+0200] {processor.py:186} INFO - Started process (PID=31953) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:16:54.890+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:16:54.894+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:16:54.893+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:16:54.899+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:16:54.898+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:16:54.900+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:16:54.900+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:16:54.900+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:16:54.918+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-18T14:18:03.527+0200] {processor.py:186} INFO - Started process (PID=32190) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:18:03.528+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:18:03.530+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:18:03.530+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:18:03.534+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:18:03.534+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:18:03.535+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:18:03.534+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:18:03.535+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:18:03.546+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T14:19:15.488+0200] {processor.py:186} INFO - Started process (PID=32769) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:19:15.490+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:19:15.492+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:19:15.492+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:19:15.496+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:19:15.495+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:19:15.497+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:19:15.496+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:19:15.497+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:19:15.508+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T14:20:28.869+0200] {processor.py:186} INFO - Started process (PID=34320) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:20:28.871+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:20:28.874+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:20:28.874+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:20:28.878+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:20:28.878+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:20:28.879+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:20:28.878+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:20:28.879+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:20:28.891+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-03-18T14:21:32.725+0200] {processor.py:186} INFO - Started process (PID=35948) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:21:32.727+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:21:32.730+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:21:32.729+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:21:32.735+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:21:32.734+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:21:32.736+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:21:32.735+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:21:32.736+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:21:32.753+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-03-18T14:22:34.682+0200] {processor.py:186} INFO - Started process (PID=36237) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:22:34.683+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:22:34.685+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:22:34.685+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:22:34.690+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:22:34.689+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:22:34.690+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:22:34.690+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:22:34.691+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:22:34.703+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-18T14:23:38.096+0200] {processor.py:186} INFO - Started process (PID=36603) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:23:38.098+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:23:38.102+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:23:38.102+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:23:38.109+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:23:38.108+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:23:38.109+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:23:38.109+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:23:38.110+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:23:38.124+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-03-18T14:24:39.827+0200] {processor.py:186} INFO - Started process (PID=37083) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:24:39.829+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:24:39.832+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:24:39.831+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:24:39.836+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:24:39.836+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:24:39.837+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:24:39.837+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:24:39.837+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:24:39.854+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-03-18T14:25:59.039+0200] {processor.py:186} INFO - Started process (PID=37515) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:25:59.040+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:25:59.042+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:25:59.042+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:25:59.046+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:25:59.045+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:25:59.046+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:25:59.046+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:25:59.047+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:25:59.058+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-18T14:27:04.690+0200] {processor.py:186} INFO - Started process (PID=37883) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:27:04.691+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:27:04.694+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:27:04.693+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:27:04.698+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:27:04.698+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:27:04.699+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:27:04.699+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:27:04.700+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:27:04.711+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-18T14:28:26.090+0200] {processor.py:186} INFO - Started process (PID=38456) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:28:26.092+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:28:26.099+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:28:26.097+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:28:26.108+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:28:26.107+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:28:26.109+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:28:26.109+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:28:26.110+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:28:26.129+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2025-03-18T14:29:44.051+0200] {processor.py:186} INFO - Started process (PID=38939) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:29:44.052+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:29:44.055+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:29:44.055+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:29:44.059+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:29:44.058+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:29:44.059+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:29:44.059+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:29:44.060+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:29:44.071+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T14:30:59.384+0200] {processor.py:186} INFO - Started process (PID=39417) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:30:59.385+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:30:59.389+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:30:59.388+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:30:59.394+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:30:59.393+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:30:59.394+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:30:59.394+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:30:59.395+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:30:59.411+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-03-18T14:32:19.118+0200] {processor.py:186} INFO - Started process (PID=39960) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:32:19.119+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:32:19.121+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:32:19.121+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:32:19.125+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:32:19.125+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:32:19.126+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:32:19.126+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:32:19.126+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:32:19.138+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T14:33:28.548+0200] {processor.py:186} INFO - Started process (PID=40408) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:33:28.550+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:33:28.552+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:33:28.552+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:33:28.556+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:33:28.556+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:33:28.557+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:33:28.556+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:33:28.557+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:33:28.568+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T14:34:47.496+0200] {processor.py:186} INFO - Started process (PID=40944) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:34:47.498+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:34:47.501+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:34:47.500+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:34:47.505+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:34:47.504+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:34:47.505+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:34:47.505+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:34:47.505+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:34:47.517+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-03-18T14:35:55.022+0200] {processor.py:186} INFO - Started process (PID=41381) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:35:55.023+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:35:55.027+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:35:55.026+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:35:55.032+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:35:55.031+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:35:55.033+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:35:55.033+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:35:55.033+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:35:55.050+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-03-18T14:36:58.995+0200] {processor.py:186} INFO - Started process (PID=41806) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:36:58.996+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:36:58.999+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:36:58.999+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:36:59.005+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:36:59.004+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:36:59.005+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:36:59.005+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:36:59.006+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:36:59.019+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-18T14:38:12.220+0200] {processor.py:186} INFO - Started process (PID=42345) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:38:12.221+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:38:12.224+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:38:12.224+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:38:12.228+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:38:12.228+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:38:12.229+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:38:12.229+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:38:12.229+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:38:12.242+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-03-18T14:39:15.065+0200] {processor.py:186} INFO - Started process (PID=42553) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:39:15.066+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:39:15.070+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:39:15.069+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:39:15.073+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:39:15.073+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:39:15.074+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:39:15.074+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:39:15.074+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:39:15.087+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-18T14:40:14.070+0200] {processor.py:186} INFO - Started process (PID=42761) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:40:14.072+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:40:14.076+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:40:14.075+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:40:14.081+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:40:14.080+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:40:14.082+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:40:14.081+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:40:14.082+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:40:14.099+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-03-18T14:41:15.821+0200] {processor.py:186} INFO - Started process (PID=42912) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:41:15.822+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:41:15.824+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:41:15.824+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:41:15.828+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:41:15.827+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:41:15.828+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:41:15.828+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:41:15.828+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:41:15.840+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T14:42:14.655+0200] {processor.py:186} INFO - Started process (PID=43352) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:42:14.656+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:42:14.659+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:42:14.658+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:42:14.663+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:42:14.662+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:42:14.664+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:42:14.663+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:42:14.664+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:42:14.676+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T14:43:19.387+0200] {processor.py:186} INFO - Started process (PID=43925) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:43:19.389+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:43:19.392+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:43:19.392+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:43:19.399+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:43:19.398+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:43:19.400+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:43:19.400+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:43:19.400+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:43:19.419+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-03-18T14:44:33.115+0200] {processor.py:186} INFO - Started process (PID=44179) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:44:33.117+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:44:33.120+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:44:33.119+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:44:33.124+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:44:33.124+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:44:33.125+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:44:33.124+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:44:33.125+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:44:33.137+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-03-18T14:45:36.151+0200] {processor.py:186} INFO - Started process (PID=44359) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:45:36.152+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:45:36.155+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:45:36.155+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:45:36.159+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:45:36.158+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:45:36.160+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:45:36.160+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:45:36.160+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:45:36.172+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T14:46:35.508+0200] {processor.py:186} INFO - Started process (PID=44510) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:46:35.509+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:46:35.512+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:46:35.511+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:46:35.515+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:46:35.515+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:46:35.516+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:46:35.516+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:46:35.516+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:46:35.527+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-18T14:47:39.219+0200] {processor.py:186} INFO - Started process (PID=44813) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:47:39.221+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:47:39.224+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:47:39.223+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:47:39.229+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:47:39.228+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:47:39.230+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:47:39.229+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:47:39.230+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:47:39.246+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-18T14:48:42.710+0200] {processor.py:186} INFO - Started process (PID=45053) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:48:42.712+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:48:42.717+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:48:42.716+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:48:42.726+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:48:42.724+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:48:42.726+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:48:42.726+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:48:42.727+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:48:42.751+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2025-03-18T14:49:43.228+0200] {processor.py:186} INFO - Started process (PID=45251) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:49:43.230+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:49:43.234+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:49:43.233+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:49:43.241+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:49:43.240+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:49:43.242+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:49:43.241+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:49:43.242+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:49:43.268+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2025-03-18T14:50:43.221+0200] {processor.py:186} INFO - Started process (PID=45437) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:50:43.223+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:50:43.227+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:50:43.226+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:50:43.236+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:50:43.235+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:50:43.237+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:50:43.236+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:50:43.237+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:50:43.254+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-03-18T14:51:45.601+0200] {processor.py:186} INFO - Started process (PID=45670) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:51:45.602+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:51:45.605+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:51:45.604+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:51:45.608+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:51:45.608+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:51:45.609+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:51:45.609+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:51:45.609+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:51:45.620+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-18T14:52:45.498+0200] {processor.py:186} INFO - Started process (PID=45830) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:52:45.499+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:52:45.503+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:52:45.502+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:52:45.509+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:52:45.508+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:52:45.510+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:52:45.510+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:52:45.510+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:52:45.526+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-03-18T14:53:49.640+0200] {processor.py:186} INFO - Started process (PID=46031) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:53:49.642+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:53:49.645+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:53:49.644+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:53:49.649+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:53:49.649+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:53:49.650+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:53:49.650+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:53:49.650+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:53:49.662+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-18T14:54:58.256+0200] {processor.py:186} INFO - Started process (PID=46212) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:54:58.258+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:54:58.260+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:54:58.260+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:54:58.264+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:54:58.263+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:54:58.264+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:54:58.264+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:54:58.265+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:54:58.278+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-18T14:55:59.819+0200] {processor.py:186} INFO - Started process (PID=46353) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:55:59.820+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:55:59.824+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:55:59.823+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:55:59.829+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:55:59.829+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:55:59.830+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:55:59.830+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:55:59.830+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:55:59.848+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-03-18T14:57:04.455+0200] {processor.py:186} INFO - Started process (PID=46491) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:57:04.457+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:57:04.461+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:57:04.460+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:57:04.466+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:57:04.465+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:57:04.466+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:57:04.466+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:57:04.466+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:57:04.481+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-18T14:58:08.031+0200] {processor.py:186} INFO - Started process (PID=46667) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:58:08.032+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:58:08.035+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:58:08.035+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:58:08.041+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:58:08.040+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:58:08.041+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:58:08.041+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:58:08.042+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:58:08.059+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-18T14:59:08.197+0200] {processor.py:186} INFO - Started process (PID=47046) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:59:08.198+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T14:59:08.202+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:59:08.201+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:59:08.206+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:59:08.205+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T14:59:08.206+0200] {logging_mixin.py:190} INFO - [2025-03-18T14:59:08.206+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T14:59:08.206+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T14:59:08.225+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-03-18T15:00:11.679+0200] {processor.py:186} INFO - Started process (PID=47245) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:00:11.680+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:00:11.683+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:00:11.682+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:00:11.686+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:00:11.686+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:00:11.687+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:00:11.687+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:00:11.687+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:00:11.699+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T15:01:11.656+0200] {processor.py:186} INFO - Started process (PID=47416) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:01:11.658+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:01:11.661+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:01:11.661+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:01:11.665+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:01:11.665+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:01:11.666+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:01:11.666+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:01:11.666+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:01:11.677+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-18T15:02:08.620+0200] {processor.py:186} INFO - Started process (PID=47540) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:02:08.621+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:02:08.624+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:02:08.623+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:02:08.628+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:02:08.627+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:02:08.629+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:02:08.628+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:02:08.629+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:02:08.641+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T15:03:04.419+0200] {processor.py:186} INFO - Started process (PID=47694) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:03:04.420+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:03:04.423+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:03:04.423+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:03:04.428+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:03:04.427+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:03:04.429+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:03:04.428+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:03:04.429+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:03:04.443+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-18T15:04:01.975+0200] {processor.py:186} INFO - Started process (PID=47842) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:04:01.977+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:04:01.980+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:04:01.979+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:04:01.984+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:04:01.983+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:04:01.984+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:04:01.984+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:04:01.985+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:04:01.996+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-18T15:04:59.311+0200] {processor.py:186} INFO - Started process (PID=48074) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:04:59.313+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:04:59.315+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:04:59.315+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:04:59.319+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:04:59.318+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:04:59.320+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:04:59.319+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:04:59.320+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:04:59.331+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:05:58.093+0200] {processor.py:186} INFO - Started process (PID=48227) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:05:58.095+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:05:58.099+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:05:58.098+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:05:58.104+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:05:58.103+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:05:58.104+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:05:58.104+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:05:58.104+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:05:58.116+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-18T15:06:59.531+0200] {processor.py:186} INFO - Started process (PID=48396) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:06:59.532+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:06:59.535+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:06:59.534+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:06:59.538+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:06:59.538+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:06:59.539+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:06:59.538+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:06:59.539+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:06:59.551+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:07:57.648+0200] {processor.py:186} INFO - Started process (PID=48544) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:07:57.650+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:07:57.652+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:07:57.652+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:07:57.657+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:07:57.656+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:07:57.657+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:07:57.657+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:07:57.657+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:07:57.668+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T15:08:55.555+0200] {processor.py:186} INFO - Started process (PID=48712) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:08:55.556+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:08:55.558+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:08:55.558+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:08:55.562+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:08:55.561+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:08:55.562+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:08:55.562+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:08:55.563+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:08:55.574+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-18T15:09:54.591+0200] {processor.py:186} INFO - Started process (PID=48794) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:09:54.592+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:09:54.595+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:09:54.594+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:09:54.598+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:09:54.598+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:09:54.599+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:09:54.599+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:09:54.599+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:09:54.609+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-03-18T15:10:52.966+0200] {processor.py:186} INFO - Started process (PID=49013) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:10:52.967+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:10:52.970+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:10:52.969+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:10:52.974+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:10:52.973+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:10:52.974+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:10:52.974+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:10:52.974+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:10:52.986+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:11:49.887+0200] {processor.py:186} INFO - Started process (PID=49158) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:11:49.889+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:11:49.891+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:11:49.891+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:11:49.895+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:11:49.894+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:11:49.896+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:11:49.895+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:11:49.896+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:11:49.907+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:12:49.116+0200] {processor.py:186} INFO - Started process (PID=49321) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:12:49.118+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:12:49.121+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:12:49.120+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:12:49.125+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:12:49.124+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:12:49.126+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:12:49.125+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:12:49.126+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:12:49.143+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-03-18T15:13:46.636+0200] {processor.py:186} INFO - Started process (PID=49466) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:13:46.638+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:13:46.640+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:13:46.640+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:13:46.644+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:13:46.643+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:13:46.644+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:13:46.644+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:13:46.645+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:13:46.657+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-18T15:14:47.825+0200] {processor.py:186} INFO - Started process (PID=49599) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:14:47.826+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:14:47.830+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:14:47.829+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:14:47.835+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:14:47.834+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:14:47.835+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:14:47.835+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:14:47.835+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:14:47.847+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-18T15:15:48.397+0200] {processor.py:186} INFO - Started process (PID=49746) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:15:48.398+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:15:48.401+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:15:48.401+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:15:48.405+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:15:48.405+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:15:48.406+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:15:48.405+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:15:48.406+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:15:48.419+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-18T15:16:46.801+0200] {processor.py:186} INFO - Started process (PID=49883) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:16:46.803+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:16:46.805+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:16:46.805+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:16:46.809+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:16:46.808+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:16:46.809+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:16:46.809+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:16:46.809+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:16:46.821+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T15:17:53.053+0200] {processor.py:186} INFO - Started process (PID=50074) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:17:53.054+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:17:53.057+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:17:53.056+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:17:53.061+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:17:53.060+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:17:53.061+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:17:53.061+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:17:53.061+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:17:53.072+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-18T15:18:51.312+0200] {processor.py:186} INFO - Started process (PID=50245) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:18:51.313+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:18:51.316+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:18:51.316+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:18:51.320+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:18:51.320+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:18:51.321+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:18:51.321+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:18:51.321+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:18:51.331+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:19:47.247+0200] {processor.py:186} INFO - Started process (PID=50398) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:19:47.248+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:19:47.251+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:19:47.250+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:19:47.255+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:19:47.254+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:19:47.255+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:19:47.255+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:19:47.256+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:19:47.266+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:20:46.932+0200] {processor.py:186} INFO - Started process (PID=50551) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:20:46.933+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:20:46.935+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:20:46.935+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:20:46.939+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:20:46.938+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:20:46.939+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:20:46.939+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:20:46.939+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:20:46.951+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-18T15:21:46.395+0200] {processor.py:186} INFO - Started process (PID=50697) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:21:46.396+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:21:46.398+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:21:46.398+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:21:46.402+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:21:46.401+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:21:46.402+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:21:46.402+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:21:46.403+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:21:46.414+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:22:45.895+0200] {processor.py:186} INFO - Started process (PID=50846) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:22:45.896+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:22:45.899+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:22:45.898+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:22:45.902+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:22:45.902+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:22:45.903+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:22:45.903+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:22:45.903+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:22:45.914+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:23:45.618+0200] {processor.py:186} INFO - Started process (PID=50995) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:23:45.620+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:23:45.623+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:23:45.622+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:23:45.627+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:23:45.626+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:23:45.627+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:23:45.627+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:23:45.628+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:23:45.639+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:24:42.540+0200] {processor.py:186} INFO - Started process (PID=51128) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:24:42.542+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:24:42.544+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:24:42.543+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:24:42.548+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:24:42.547+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:24:42.549+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:24:42.549+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:24:42.549+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:24:42.560+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T15:25:41.016+0200] {processor.py:186} INFO - Started process (PID=51241) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:25:41.017+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T15:25:41.021+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:25:41.020+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:25:41.026+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:25:41.025+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T15:25:41.026+0200] {logging_mixin.py:190} INFO - [2025-03-18T15:25:41.026+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T15:25:41.027+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T15:25:41.039+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-18T21:04:09.639+0200] {processor.py:186} INFO - Started process (PID=51632) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:04:09.641+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:04:09.644+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:04:09.644+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:04:09.650+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:04:09.649+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:04:09.650+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:04:09.650+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:04:09.650+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:04:09.662+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-18T21:05:09.423+0200] {processor.py:186} INFO - Started process (PID=51821) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:05:09.424+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:05:09.426+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:05:09.426+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:05:09.430+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:05:09.429+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:05:09.430+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:05:09.430+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:05:09.431+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:05:09.441+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-18T21:06:06.680+0200] {processor.py:186} INFO - Started process (PID=52006) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:06:06.682+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:06:06.685+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:06:06.684+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:06:06.689+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:06:06.688+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:06:06.689+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:06:06.689+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:06:06.690+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:06:06.703+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-18T21:07:00.083+0200] {processor.py:186} INFO - Started process (PID=52192) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:07:00.084+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:07:00.086+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:07:00.086+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:07:00.090+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:07:00.089+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:07:00.090+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:07:00.090+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:07:00.090+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:07:00.104+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-18T21:07:57.011+0200] {processor.py:186} INFO - Started process (PID=52397) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:07:57.013+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:07:57.016+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:07:57.016+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:07:57.022+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:07:57.021+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:07:57.022+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:07:57.022+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:07:57.022+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:07:57.035+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-03-18T21:08:56.220+0200] {processor.py:186} INFO - Started process (PID=52590) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:08:56.221+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:08:56.224+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:08:56.223+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:08:56.227+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:08:56.227+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:08:56.228+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:08:56.227+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:08:56.228+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:08:56.239+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-03-18T21:09:54.953+0200] {processor.py:186} INFO - Started process (PID=52823) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:09:54.956+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:09:54.963+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:09:54.961+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:09:54.977+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:09:54.975+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:09:54.978+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:09:54.977+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:09:54.979+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:09:55.003+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-03-18T21:10:54.277+0200] {processor.py:186} INFO - Started process (PID=53032) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:10:54.278+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:10:54.282+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:10:54.281+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:10:54.287+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:10:54.287+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:10:54.288+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:10:54.288+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:10:54.288+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:10:54.300+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-18T21:11:55.256+0200] {processor.py:186} INFO - Started process (PID=53253) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:11:55.257+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:11:55.260+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:11:55.259+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:11:55.263+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:11:55.263+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:11:55.264+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:11:55.264+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:11:55.264+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:11:55.275+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-18T21:12:53.531+0200] {processor.py:186} INFO - Started process (PID=53463) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:12:53.532+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:12:53.535+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:12:53.535+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:12:53.539+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:12:53.539+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:12:53.540+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:12:53.539+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:12:53.540+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:12:53.552+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-18T21:13:47.714+0200] {processor.py:186} INFO - Started process (PID=53663) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:13:47.716+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:13:47.718+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:13:47.718+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:13:47.722+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:13:47.721+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:13:47.722+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:13:47.722+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:13:47.722+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:13:47.733+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-18T21:14:46.471+0200] {processor.py:186} INFO - Started process (PID=53918) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:14:46.472+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:14:46.476+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:14:46.475+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:14:46.481+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:14:46.480+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:14:46.482+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:14:46.481+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:14:46.482+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:14:46.498+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-18T21:15:49.778+0200] {processor.py:186} INFO - Started process (PID=54181) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:15:49.779+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:15:49.782+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:15:49.781+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:15:49.786+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:15:49.785+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:15:49.786+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:15:49.786+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:15:49.786+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:15:49.799+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-18T21:16:55.860+0200] {processor.py:186} INFO - Started process (PID=54420) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:16:55.862+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:16:55.866+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:16:55.865+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:16:55.872+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:16:55.871+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:16:55.872+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:16:55.872+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:16:55.873+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:16:55.885+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-03-18T21:17:59.067+0200] {processor.py:186} INFO - Started process (PID=54645) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:17:59.069+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-18T21:17:59.073+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:17:59.072+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:17:59.077+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:17:59.076+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-18T21:17:59.077+0200] {logging_mixin.py:190} INFO - [2025-03-18T21:17:59.077+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-18T21:17:59.077+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-18T21:17:59.090+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
