[2025-03-12T14:17:20.823+0200] {processor.py:186} INFO - Started process (PID=134339) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:17:20.827+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:17:20.838+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:17:20.836+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:17:20.855+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:17:20.853+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:17:20.856+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:17:20.856+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:17:20.857+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:17:20.877+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-03-12T14:18:25.590+0200] {processor.py:186} INFO - Started process (PID=134695) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:18:25.591+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:18:25.594+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:18:25.593+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:18:25.598+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:18:25.597+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:18:25.599+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:18:25.598+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:18:25.599+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:18:25.610+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-12T14:19:24.838+0200] {processor.py:186} INFO - Started process (PID=134952) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:19:24.839+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:19:24.842+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:19:24.841+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:19:24.846+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:19:24.846+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:19:24.847+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:19:24.847+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:19:24.847+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:19:24.859+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-12T14:20:22.440+0200] {processor.py:186} INFO - Started process (PID=135112) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:20:22.441+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:20:22.444+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:20:22.443+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:20:22.448+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:20:22.448+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:20:22.449+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:20:22.449+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:20:22.449+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:20:22.461+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-12T14:21:19.536+0200] {processor.py:186} INFO - Started process (PID=135305) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:21:19.537+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:21:19.539+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:21:19.539+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:21:19.543+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:21:19.542+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:21:19.543+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:21:19.543+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:21:19.544+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:21:19.556+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-12T14:22:14.685+0200] {processor.py:186} INFO - Started process (PID=135527) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:22:14.687+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:22:14.691+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:22:14.691+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:22:14.697+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:22:14.697+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:22:14.698+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:22:14.698+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:22:14.698+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:22:14.713+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-03-12T14:23:20.067+0200] {processor.py:186} INFO - Started process (PID=136436) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:23:20.068+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:23:20.071+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:23:20.071+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:23:20.077+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:23:20.076+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:23:20.077+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:23:20.077+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:23:20.077+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:23:20.093+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-03-12T14:24:29.950+0200] {processor.py:186} INFO - Started process (PID=136731) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:24:29.951+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:24:29.954+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:24:29.953+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:24:29.959+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:24:29.958+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:24:29.959+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:24:29.959+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:24:29.960+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:24:29.971+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-12T14:25:26.899+0200] {processor.py:186} INFO - Started process (PID=136888) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:25:26.901+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:25:26.904+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:25:26.903+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:25:26.908+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:25:26.908+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:25:26.909+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:25:26.908+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:25:26.909+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:25:26.923+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-12T14:26:26.186+0200] {processor.py:186} INFO - Started process (PID=137100) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:26:26.187+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:26:26.190+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:26:26.189+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:26:26.194+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:26:26.193+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:26:26.195+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:26:26.194+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:26:26.195+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:26:26.207+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-12T14:27:28.610+0200] {processor.py:186} INFO - Started process (PID=137320) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:27:28.611+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:27:28.614+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:27:28.614+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:27:28.619+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:27:28.618+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:27:28.619+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:27:28.619+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:27:28.619+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:27:28.632+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-12T14:28:30.449+0200] {processor.py:186} INFO - Started process (PID=137489) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:28:30.450+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:28:30.453+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:28:30.452+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:28:30.457+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:28:30.456+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:28:30.457+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:28:30.457+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:28:30.457+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:28:30.470+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-12T14:29:28.471+0200] {processor.py:186} INFO - Started process (PID=138295) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:29:28.472+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:29:28.474+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:29:28.474+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:29:28.479+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:29:28.478+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:29:28.479+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:29:28.479+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:29:28.479+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:29:28.491+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-12T14:30:28.189+0200] {processor.py:186} INFO - Started process (PID=138735) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:30:28.191+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:30:28.194+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:30:28.193+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:30:28.199+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:30:28.198+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:30:28.199+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:30:28.199+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:30:28.199+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:30:28.211+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-12T14:31:31.879+0200] {processor.py:186} INFO - Started process (PID=138957) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:31:31.880+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:31:31.882+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:31:31.882+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:31:31.887+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:31:31.886+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:31:31.887+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:31:31.887+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:31:31.887+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:31:31.900+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-12T14:32:35.484+0200] {processor.py:186} INFO - Started process (PID=139565) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:32:35.486+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:32:35.489+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:32:35.488+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:32:35.496+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:32:35.495+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:32:35.496+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:32:35.496+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:32:35.497+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:32:35.516+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-03-12T14:33:38.371+0200] {processor.py:186} INFO - Started process (PID=139898) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:33:38.372+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:33:38.375+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:33:38.375+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:33:38.380+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:33:38.379+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:33:38.380+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:33:38.380+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:33:38.380+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:33:38.396+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-12T14:34:43.227+0200] {processor.py:186} INFO - Started process (PID=140122) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:34:43.228+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:34:43.231+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:34:43.231+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:34:43.236+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:34:43.235+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:34:43.237+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:34:43.237+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:34:43.237+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:34:43.250+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-03-12T14:35:46.655+0200] {processor.py:186} INFO - Started process (PID=140317) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:35:46.656+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:35:46.659+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:35:46.659+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:35:46.663+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:35:46.662+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:35:46.664+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:35:46.664+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:35:46.664+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:35:46.676+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-03-12T14:36:52.778+0200] {processor.py:186} INFO - Started process (PID=140510) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:36:52.779+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:36:52.781+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:36:52.781+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:36:52.786+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:36:52.785+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:36:52.786+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:36:52.786+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:36:52.786+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:36:52.798+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-12T14:37:56.669+0200] {processor.py:186} INFO - Started process (PID=140645) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:37:56.670+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:37:56.673+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:37:56.672+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:37:56.677+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:37:56.676+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:37:56.677+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:37:56.677+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:37:56.677+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:37:56.688+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-12T14:39:02.460+0200] {processor.py:186} INFO - Started process (PID=140726) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:39:02.462+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:39:02.465+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:39:02.464+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:39:02.470+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:39:02.469+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:39:02.470+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:39:02.470+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:39:02.470+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:39:02.482+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-12T14:40:08.460+0200] {processor.py:186} INFO - Started process (PID=140833) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:40:08.461+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:40:08.464+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:40:08.463+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:40:08.468+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:40:08.467+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:40:08.468+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:40:08.468+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:40:08.469+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:40:08.480+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-12T14:41:11.534+0200] {processor.py:186} INFO - Started process (PID=141103) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:41:11.535+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:41:11.538+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:41:11.538+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:41:11.544+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:41:11.542+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:41:11.545+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:41:11.544+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:41:11.545+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:41:11.557+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-12T14:42:11.066+0200] {processor.py:186} INFO - Started process (PID=141297) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:42:11.067+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:42:11.070+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:42:11.069+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:42:11.074+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:42:11.073+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:42:11.074+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:42:11.074+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:42:11.074+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:42:11.087+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-12T14:43:11.756+0200] {processor.py:186} INFO - Started process (PID=141497) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:43:11.758+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:43:11.760+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:43:11.760+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:43:11.764+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:43:11.763+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:43:11.764+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:43:11.764+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:43:11.764+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:43:11.781+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-03-12T14:44:12.540+0200] {processor.py:186} INFO - Started process (PID=141667) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:44:12.542+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:44:12.546+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:44:12.545+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:44:12.551+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:44:12.550+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:44:12.551+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:44:12.551+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:44:12.551+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:44:12.565+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-03-12T14:45:12.921+0200] {processor.py:186} INFO - Started process (PID=141857) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:45:12.922+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:45:12.925+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:45:12.924+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:45:12.929+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:45:12.928+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:45:12.929+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:45:12.929+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:45:12.929+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:45:12.943+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-12T14:46:10.902+0200] {processor.py:186} INFO - Started process (PID=142071) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:46:10.904+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:46:10.906+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:46:10.906+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:46:10.911+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:46:10.910+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:46:10.911+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:46:10.911+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:46:10.911+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:46:10.924+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-12T14:48:55.523+0200] {processor.py:186} INFO - Started process (PID=142565) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:48:55.524+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:48:55.527+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:48:55.526+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:48:55.531+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:48:55.531+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:48:55.532+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:48:55.531+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:48:55.532+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:48:55.543+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-12T14:50:28.134+0200] {processor.py:186} INFO - Started process (PID=142919) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:50:28.135+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:50:28.138+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:50:28.137+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:50:28.142+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:50:28.142+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:50:28.143+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:50:28.143+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:50:28.143+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:50:28.155+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-12T14:51:32.810+0200] {processor.py:186} INFO - Started process (PID=143150) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:51:32.812+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:51:32.815+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:51:32.814+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:51:32.821+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:51:32.820+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:51:32.822+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:51:32.822+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:51:32.822+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:51:32.835+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-12T14:52:42.905+0200] {processor.py:186} INFO - Started process (PID=143368) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:52:42.906+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:52:42.909+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:52:42.909+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:52:42.917+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:52:42.917+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:52:42.918+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:52:42.917+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:52:42.918+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:52:42.930+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-12T14:54:06.574+0200] {processor.py:186} INFO - Started process (PID=143628) to work on /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:54:06.587+0200] {processor.py:914} INFO - Processing file /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-12T14:54:06.608+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:54:06.592+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:54:06.646+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:54:06.644+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-12T14:54:06.647+0200] {logging_mixin.py:190} INFO - [2025-03-12T14:54:06.647+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-12T14:54:06.647+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-12T14:54:06.684+0200] {processor.py:208} INFO - Processing /home/munyah/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.137 seconds
